apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsd-ui-deployment
  labels:
    app: fsd-ui-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fsd-ui-deployment
  template:
    metadata:
      labels:
        app: fsd-ui-deployment
    spec:
      containers:
        - name: angular-app-cont
          image: nilesh/final-test-frontend
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fsd-ui-service
spec:
  type: LoadBalancer
  selector:
    app:  fsd-ui--deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080